name: higrow
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  # animated_toggle_switch: ^0.8.5
  get: ^4.7.2
  camera: ^0.11.2
  shared_preferences: ^2.5.3
  http: ^1.4.0
  intl: ^0.20.2
  mockito: ^5.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

 
  assets:
    - assets/images/image.png
    - assets/images/kids_jump.png
    - assets/images/logo_with_white.png
    - assets/images/logo.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic


